route:
  group_by: ['alertname', 'job']

  group_wait: 5s
  group_interval: 1m
  repeat_interval: 1h

  receiver: discord

receivers:
- name: discord
  discord_configs:
  - webhook_url: 'https://discord.com/api/webhooks/blablablabla'