# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 192.168.137.1:9093

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["192.168.137.1:9090"]

  - job_name: windows
    static_configs:
      - targets: ["192.168.137.1:9182"]

  - job_name: loki
    static_configs:
      - targets: ["192.168.137.1:3100"]
